In [1]:
from tensorflow.keras.datasets import fashion_mnist
import numpy as np
import matplotlib.pyplot as plt
from tqdm.auto import tqdm
import seaborn as sns
import pandas as pd

C:\Users\Mohsen\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [23]:
class MaxNet:
    def __init__(self, epsilon=0.15, verbose=True):
        self.epsilon = epsilon
        self.verbose = verbose
    
    def f(self, x):
        return max(0, x)
    
    def vprint(self, a):
        if self.verbose:
            print(a)
    
    def max(self, x):
        a = np.array(x)
        self.vprint(a)
        while (a > 0).sum() > 1:
            a_old = a.copy()
            for i in range(len(a)):
                a[i] = self.f(a_old[i] - self.epsilon * np.sum(np.delete(a_old, i)))
            self.vprint(a)
        return np.argmax(a), x[np.argmax(a)]
        
maxnet = MaxNet(epsilon=0.15)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
maxnet.max(x=[1.2, 1.1, 1, 0.9, 0.95, 1.15])

[ 1.200  1.100  1.000  0.900  0.950  1.150]
[ 0.435  0.320  0.205  0.090  0.148  0.377]
[ 0.264  0.132  0.000  0.000  0.000  0.198]
[ 0.215  0.062  0.000  0.000  0.000  0.139]
[ 0.184  0.010  0.000  0.000  0.000  0.097]
[ 0.168  0.000  0.000  0.000  0.000  0.068]
[ 0.158  0.000  0.000  0.000  0.000  0.043]
[ 0.152  0.000  0.000  0.000  0.000  0.019]
[ 0.149  0.000  0.000  0.000  0.000  0.000]


(0, 1.2)

# a)

In [24]:
class MaxNetBeta:
    def __init__(self, epsilon=0.15, min_value=0):
        self.epsilon = epsilon
        self.min_value = min_value
    
    def f(self, x):
        return max(0, x)
    
    def max(self, x):
        a = np.array(x) - self.min_value
        print(a)
        while (a > 0).sum() > 1:
            a_old = a.copy()
            for i in range(len(a)):
                a[i] = self.f(a_old[i] - self.epsilon * np.sum(np.delete(a_old, i)))
            print(a)
        return np.argmax(a), x[np.argmax(a)]
        
maxnet = MaxNetBeta(epsilon=0.15, min_value = -1)
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})
maxnet.max(x=[-1, -0.5, 1, 0.9, 0.95, 1.15])

[ 0.000  0.500  2.000  1.900  1.950  2.150]
[ 0.000  0.000  1.025  0.910  0.967  1.197]
[ 0.000  0.000  0.564  0.432  0.498  0.762]
[ 0.000  0.000  0.310  0.158  0.234  0.538]
[ 0.000  0.000  0.171  0.000  0.083  0.433]
[ 0.000  0.000  0.093  0.000  0.000  0.395]
[ 0.000  0.000  0.034  0.000  0.000  0.381]
[ 0.000  0.000  0.000  0.000  0.000  0.376]


(5, 1.15)

# b)

In [29]:
x = [1.2, 1.1, 1, 0.9, 0.95, 1.15, 2]
sorted_x = []
for i in range(len(x)):
    maxnet = MaxNet(epsilon=0.15, verbose=False)
    i, v = maxnet.max(x)
    x.pop(i)
    sorted_x.append(v)
sorted_x

[2, 1.2, 1.15, 1.1, 1, 0.95, 0.9]

# c)

In [39]:
x = [1.2, 1.1, 1, 0.9, 0.95, 1.15, 2]
sorted_x = []
for i in range(len(x)):
    maxnet = MaxNet(epsilon=0.15, verbose=False)
    i, v = maxnet.max(x)
    x.pop(i)
    sorted_x.insert(0, v)
sorted_x

[0.9, 0.95, 1, 1.1, 1.15, 1.2, 2]